/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/car-reservation-confirm`; params?: Router.UnknownInputParams; } | { pathname: `/car-reservation`; params?: Router.UnknownInputParams; } | { pathname: `/gesture-handler`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/payment`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/reservation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/booking` | `/booking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/bookingStack` | `/bookingStack`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/searchStack` | `/searchStack`; params?: Router.UnknownInputParams; } | { pathname: `${'/(search)'}/parking_spots` | `/parking_spots`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/car-reservation-confirm`; params?: Router.UnknownOutputParams; } | { pathname: `/car-reservation`; params?: Router.UnknownOutputParams; } | { pathname: `/gesture-handler`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/payment`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/reservation`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/booking` | `/booking`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(pages)'}/bookingStack` | `/bookingStack`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(pages)'}/searchStack` | `/searchStack`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(search)'}/parking_spots` | `/parking_spots`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/car-reservation-confirm${`?${string}` | `#${string}` | ''}` | `/car-reservation${`?${string}` | `#${string}` | ''}` | `/gesture-handler${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/payment${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/reservation${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/booking${`?${string}` | `#${string}` | ''}` | `/booking${`?${string}` | `#${string}` | ''}` | `${'/(pages)'}/bookingStack${`?${string}` | `#${string}` | ''}` | `/bookingStack${`?${string}` | `#${string}` | ''}` | `${'/(pages)'}/searchStack${`?${string}` | `#${string}` | ''}` | `/searchStack${`?${string}` | `#${string}` | ''}` | `${'/(search)'}/parking_spots${`?${string}` | `#${string}` | ''}` | `/parking_spots${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/car-reservation-confirm`; params?: Router.UnknownInputParams; } | { pathname: `/car-reservation`; params?: Router.UnknownInputParams; } | { pathname: `/gesture-handler`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/payment`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/reservation`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/booking` | `/booking`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/bookingStack` | `/bookingStack`; params?: Router.UnknownInputParams; } | { pathname: `${'/(pages)'}/searchStack` | `/searchStack`; params?: Router.UnknownInputParams; } | { pathname: `${'/(search)'}/parking_spots` | `/parking_spots`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; };
    }
  }
}
